# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gwsm < Formula
  desc "Kubernetes ConfigMaps + https://github.com/cyberark/summon + AWS Secrets Manager"
  homepage "https://goodwaygroup.github.io/gwsm/"
  version "1.1.1"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/GoodwayGroup/gwsm/releases/download/v1.1.1/gwsm_1.1.1_darwin_amd64.tar.gz"
    sha256 "7f1bf2a7bae37d4ce319128007379fdddbb578479006ea27ad06afe38bdbc207"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/GoodwayGroup/gwsm/releases/download/v1.1.1/gwsm_1.1.1_darwin_arm64.tar.gz"
    sha256 "5e1ea6b618df7cc3453603268baf68539e24546184ca95d3a73d02f7560dd863"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/GoodwayGroup/gwsm/releases/download/v1.1.1/gwsm_1.1.1_linux_amd64.tar.gz"
    sha256 "edc2c5a76eca8c0b37be9a136491c225080bd164c5aa8532075de732f156bd0d"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/GoodwayGroup/gwsm/releases/download/v1.1.1/gwsm_1.1.1_linux_armv6.tar.gz"
    sha256 "9c3c93fa77cd5a64839e1136432d7c792cac7b947db11d9699db666ff1a2b85e"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/GoodwayGroup/gwsm/releases/download/v1.1.1/gwsm_1.1.1_linux_arm64.tar.gz"
    sha256 "6b2dc61149f71e2404ca011c47438022a2e0d6f4f9a69c1bb10da487a6901c71"
  end

  def install
    bin.install "gwsm"
  end

  test do
    system "#{bin}/gwsm --help"
  end
end
